name: app
description: "Scripting Demo App"
publish_to: "none"
version: 1.0.0

environment:
    sdk: ^3.10.1

dependencies:
    flutter:
        sdk: flutter
    get: ^4.7.3
    get_storage: ^2.1.1
    grpc: ^5.1.0
    protobuf: ^6.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/cert/root_ca.crt
